import Foundation

/// Builds role-aware gas switch order for planner helper views. Bühlmann deco stops are generated by `BuhlmannEngine`.
enum PlannerGasSchedule {
    struct SwitchPoint: Hashable {
        let depthMeters: Double
        let gas: GasMix
        let role: GasRole
    }

    static func bottomGas(from input: GasPlanInput) -> GasMix {
        var working = input
        working.syncLegacyGasesFromPlannerCylinders()
        return working.bottomGas
    }

    static func sortedDecoCylinders(from input: GasPlanInput) -> [PlannerCylinderEntry] {
        input.plannerCylinders
            .filter { $0.role == .deco }
            .sorted { $0.switchDepthMeters > $1.switchDepthMeters }
    }

    static func sortedTravelCylinders(from input: GasPlanInput) -> [PlannerCylinderEntry] {
        input.plannerCylinders
            .filter { $0.role == .travel }
            .sorted { $0.switchDepthMeters > $1.switchDepthMeters }
    }

    static func bailoutCylinders(from input: GasPlanInput) -> [PlannerCylinderEntry] {
        input.plannerCylinders.filter { $0.role == .bailout }
    }

    /// Descent switch points from shallow to deep (travel segments, then back gas at max depth).
    static func descentSwitchPoints(input: GasPlanInput) -> [SwitchPoint] {
        let maxDepth = input.plannedDepthMeters
        var points: [SwitchPoint] = []

        for travel in sortedTravelCylinders(from: input) {
            let depth = travel.switchDepthMeters
            guard depth > 0.5, depth < maxDepth - 0.5 else { continue }
            points.append(SwitchPoint(depthMeters: depth, gas: travel.gas, role: .travel))
        }

        points.append(SwitchPoint(depthMeters: maxDepth, gas: bottomGas(from: input), role: .bottom))
        return points.sorted { $0.depthMeters < $1.depthMeters }
    }

    /// Ascent-related travel switches between bottom and shallowest planned stop.
    static func ascentTravelSwitchPoints(input: GasPlanInput, shallowestStopDepth: Double) -> [SwitchPoint] {
        let maxDepth = input.plannedDepthMeters
        return sortedTravelCylinders(from: input).compactMap { travel in
            let depth = travel.switchDepthMeters
            guard depth > shallowestStopDepth + 0.5, depth < maxDepth - 0.5 else { return nil }
            return SwitchPoint(depthMeters: depth, gas: travel.gas, role: .travel)
        }.sorted { $0.depthMeters > $1.depthMeters }
    }

    static func hasMODBlockingIssues(input: GasPlanInput) -> Bool {
        guard PlannerInputValidator.validate(input).isValid else { return true }
        var working = input
        working.syncLegacyGasesFromPlannerCylinders()
        if !PlannerMODValidator.validatePlannerCylinders(input: working).isEmpty {
            return true
        }
        let enginePlan = BuhlmannPlanner.enginePlan(input: working)
        if enginePlan.hasBlockingIssues {
            return true
        }
        return false
    }

    static func makeDecoStop(depthMeters: Double, minutes: Int, gas: GasMix) -> DecoStop {
        let actualPPO2 = GasPlanningService.ppO2(gas: gas, depthMeters: depthMeters)
        let states: [PlannerResultState] = actualPPO2 > gas.maxPPO2 ? [.PPO2Exceeded] : []
        return DecoStop(
            depthMeters: depthMeters,
            minutes: minutes,
            gas: gas.label,
            ppO2: actualPPO2,
            maxPPO2: gas.maxPPO2,
            states: states
        )
    }

    static func roleScheduleLines(input: GasPlanInput) -> [String] {
        var lines: [String] = []
        let travels = sortedTravelCylinders(from: input)
        if !travels.isEmpty {
            let travelSummary = travels.map { "\($0.gas.label) @ \(Int($0.switchDepthMeters))m" }.joined(separator: ", ")
            lines.append(String(format: String(localized: "planner.schedule.travel"), travelSummary))
        }
        lines.append(String(format: String(localized: "planner.schedule.back_gas"), bottomGas(from: input).label, Int(input.plannedDepthMeters)))
        let decos = sortedDecoCylinders(from: input)
        if !decos.isEmpty {
            let decoSummary = decos.map { "\($0.gas.label) @ \(Int($0.switchDepthMeters))m" }.joined(separator: ", ")
            lines.append(String(format: String(localized: "planner.schedule.deco"), decoSummary))
        }
        for bailout in bailoutCylinders(from: input) {
            lines.append(
                String(
                    format: String(localized: "planner.schedule.bailout"),
                    bailout.gas.label,
                    Int(min(bailout.switchDepthMeters, bailout.modMeters))
                )
            )
        }
        return lines
    }
}
