import Foundation

/// Builds role-aware gas switch order for planner helper views. Bühlmann deco stops are generated by `BuhlmannEngine`.
enum PlannerGasSchedule {
    struct SwitchPoint: Hashable {
        let depthMeters: Double
        let gas: GasMix
        let role: GasRole
    }

    static func bottomGas(from input: GasPlanInput) -> GasMix {
        var working = input
        working.syncLegacyGasesFromPlannerCylinders()
        return working.bottomGas
    }

    /// Bottom-gas switch depth (m). Uses bottom-cylinder switch when set between surface and max depth; otherwise max depth.
    static func bottomGasSwitchDepthMeters(from input: GasPlanInput) -> Double {
        let maxDepth = input.plannedDepthMeters
        guard maxDepth.isFinite, maxDepth > 0 else { return maxDepth }
        if let bottom = input.plannerCylinders.first(where: { $0.role == .bottom }),
           bottom.switchDepthMeters > 0.5,
           bottom.switchDepthMeters < maxDepth - 0.5 {
            return bottom.switchDepthMeters
        }
        return maxDepth
    }

    static func sortedDecoCylinders(from input: GasPlanInput) -> [PlannerCylinderEntry] {
        input.plannerCylinders
            .filter { $0.role == .deco }
            .sorted { $0.switchDepthMeters > $1.switchDepthMeters }
    }

    static func sortedTravelCylinders(from input: GasPlanInput) -> [PlannerCylinderEntry] {
        input.plannerCylinders
            .filter { $0.role == .travel }
            .sorted { $0.switchDepthMeters > $1.switchDepthMeters }
    }

    static func bailoutCylinders(from input: GasPlanInput) -> [PlannerCylinderEntry] {
        input.plannerCylinders.filter { $0.role == .bailout }
    }

    /// Descent switch points from shallow to deep (travel segments, then back gas at max depth).
    static func descentSwitchPoints(input: GasPlanInput) -> [SwitchPoint] {
        let maxDepth = input.plannedDepthMeters
        var points: [SwitchPoint] = []

        for travel in sortedTravelCylinders(from: input) {
            let depth = travel.switchDepthMeters
            guard depth > 0.5, depth < maxDepth - 0.5 else { continue }
            points.append(SwitchPoint(depthMeters: depth, gas: travel.gas, role: .travel))
        }

        points.append(
            SwitchPoint(
                depthMeters: bottomGasSwitchDepthMeters(from: input),
                gas: bottomGas(from: input),
                role: .bottom
            )
        )
        return points.sorted { $0.depthMeters < $1.depthMeters }
    }

    /// Ascent-related travel switches between bottom and shallowest planned stop.
    static func ascentTravelSwitchPoints(input: GasPlanInput, shallowestStopDepth: Double) -> [SwitchPoint] {
        let maxDepth = input.plannedDepthMeters
        return sortedTravelCylinders(from: input).compactMap { travel in
            let depth = travel.switchDepthMeters
            guard depth > shallowestStopDepth + 0.5, depth < maxDepth - 0.5 else { return nil }
            return SwitchPoint(depthMeters: depth, gas: travel.gas, role: .travel)
        }.sorted { $0.depthMeters > $1.depthMeters }
    }

    static func hasMODBlockingIssues(input: GasPlanInput) -> Bool {
        guard PlannerInputValidator.validate(input).isValid else { return true }
        var working = input
        working.syncLegacyGasesFromPlannerCylinders()
        let enginePlan = BuhlmannPlanner.enginePlan(input: working)
        return enginePlan.hasBlockingIssues
    }

    static func makeDecoStop(depthMeters: Double, minutes: Int, gas: GasMix, environment: PlannerEnvironment = .seaLevelSaltWater) -> DecoStop {
        let actualPPO2 = GasPlanningService.ppO2(gas: gas, depthMeters: depthMeters, environment: environment)
        let states: [PlannerResultState] = actualPPO2 > gas.maxPPO2 ? [.PPO2Exceeded] : []
        return DecoStop(
            depthMeters: depthMeters,
            minutes: minutes,
            gas: gas.label,
            ppO2: actualPPO2,
            maxPPO2: gas.maxPPO2,
            states: states
        )
    }

    static func roleScheduleLines(input: GasPlanInput, environment: PlannerEnvironment? = nil) -> [String] {
        let resolvedEnvironment = environment ?? input.plannerEnvironment
        var lines: [String] = []
        let travels = sortedTravelCylinders(from: input)
        if !travels.isEmpty {
            let travelSummary = travels.map { "\($0.gas.label) @ \(Int($0.switchDepthMeters))m" }.joined(separator: ", ")
            lines.append(String(format: String(localized: "planner.schedule.travel"), travelSummary))
        }
        let bottomSwitch = Int(bottomGasSwitchDepthMeters(from: input))
        lines.append(
            String(
                format: String(localized: "planner.schedule.back_gas"),
                bottomGas(from: input).label,
                bottomSwitch
            )
        )
        let decos = sortedDecoCylinders(from: input)
        if !decos.isEmpty {
            let decoSummary = decos.map { "\($0.gas.label) @ \(Int($0.switchDepthMeters))m" }.joined(separator: ", ")
            lines.append(String(format: String(localized: "planner.schedule.deco"), decoSummary))
        }
        for bailout in bailoutCylinders(from: input) {
            lines.append(
                String(
                    format: String(localized: "planner.schedule.bailout"),
                    bailout.gas.label,
                    Int(min(bailout.switchDepthMeters, bailout.modMeters(environment: resolvedEnvironment)))
                )
            )
        }
        return lines
    }

    /// Warn when travel gas is present but bottom gas still switches only at max depth (default bottom switch depth).
    static func travelToBottomSwitchLimitationWarnings(
        input: GasPlanInput,
        environment: PlannerEnvironment? = nil
    ) -> [String] {
        var working = input
        working.syncLegacyGasesFromPlannerCylinders()
        let resolvedEnvironment = environment ?? working.plannerEnvironment
        guard !sortedTravelCylinders(from: working).isEmpty else { return [] }
        let bottomSwitch = bottomGasSwitchDepthMeters(from: working)
        guard abs(bottomSwitch - working.plannedDepthMeters) < 0.5 else { return [] }
        let bottom = working.bottomGas
        let ppO2AtMax = GasPlanningService.ppO2(
            gas: bottom,
            depthMeters: working.plannedDepthMeters,
            environment: resolvedEnvironment
        )
        let isTrimixWithTravel = bottom.helium > 0.001
        let isLowOxygenFraction = bottom.oxygen <= 0.18 + 1e-6
        let isHypoxicAtMaxDepth = ppO2AtMax < BuhlmannConstants.minBreathablePPO2Bar + 0.02
        if isTrimixWithTravel && (isLowOxygenFraction || isHypoxicAtMaxDepth) {
            return [String(localized: "planner.limitation.travel_bottom_switch_simplified")]
        }
        return []
    }

    /// Bailout cylinders are schedule-only in this reference planner — not passed to `BuhlmannEngine`.
    static func bailoutAvailabilityWarnings(input: GasPlanInput, environment: PlannerEnvironment? = nil) -> [String] {
        let resolvedEnvironment = environment ?? input.plannerEnvironment
        return bailoutCylinders(from: input).map { bailout in
            String(
                format: String(localized: "planner.bailout.engine_excluded"),
                bailout.gas.label,
                Int(min(bailout.switchDepthMeters, bailout.modMeters(environment: resolvedEnvironment)))
            )
        }
    }
}
